"""
This type stub file was generated by pyright.
"""

from ccxt.async_support.hitbtc import hitbtc
from ccxt.abstract.bequant import ImplicitAPI
from ccxt.base.types import Any

class bequant(hitbtc, ImplicitAPI):
    def describe(self) -> Any:
        ...
    


