"""
This type stub file was generated by pyright.
"""

from ccxt.async_support.binance import binance
from ccxt.abstract.binancecoinm import ImplicitAPI
from ccxt.base.types import Any

class binancecoinm(binance, ImplicitAPI):
    def describe(self) -> Any:
        ...
    
    async def transfer_in(self, code: str, amount, params=...):
        ...
    
    async def transfer_out(self, code: str, amount, params=...):
        ...
    


