"""
This type stub file was generated by pyright.
"""

from ccxt.pro.binance import binance
from ccxt.base.types import Any

class binanceusdm(binance):
    def describe(self) -> Any:
        ...
    


