"""
This type stub file was generated by pyright.
"""

from typing import Any

def import_string(dotted_path: str) -> Any:
    """
    Import a variable using its path and name.

    :param dotted_path: dotted module path and variable/class name
    :return: the attribute/class designated by the last name in the path
    :raise: ImportError, if the import failed

    Source: django.utils.module_loading
    """
    ...

