"""
This type stub file was generated by pyright.
"""

from typing import NewType

BLSPubkey = NewType("BLSPubkey", bytes)
BLSPrivateKey = NewType("BLSPrivateKey", int)
BLSSignature = NewType("BLSSignature", bytes)
