"""
This type stub file was generated by pyright.
"""

from ccxt.base import decimal_to_precision, errors
from ccxt import AccountSuspended, AddressPending, ArgumentsRequired, AuthenticationError, BadRequest, BadResponse, BaseError, CancelPending, DDoSProtection, DuplicateOrderId, ExchangeError, ExchangeNotAvailable, InsufficientFunds, InvalidAddress, InvalidNonce, InvalidOrder, NetworkError, NotSupported, NullResponse, OnMaintenance, OrderImmediatelyFillable, OrderNotCached, OrderNotFillable, OrderNotFound, PermissionDenied, RateLimitExceeded, RequestTimeout

__all__ = decimal_to_precision.__all__ + errors.__all__
