"""
This type stub file was generated by pyright.
"""

from ccxt.binance import binance
from ccxt.abstract.binanceus import ImplicitAPI
from ccxt.base.types import Any

class binanceus(binance, ImplicitAPI):
    def describe(self) -> Any:
        ...
    


