"""
This type stub file was generated by pyright.
"""

from ccxt.htx import htx
from ccxt.abstract.huobi import ImplicitAPI
from ccxt.base.types import Any

class huobi(htx, ImplicitAPI):
    def describe(self) -> Any:
        ...
    


