"""
This type stub file was generated by pyright.
"""

from ccxt.okx import okx
from ccxt.abstract.okxus import ImplicitAPI
from ccxt.base.types import Any

class okxus(okx, ImplicitAPI):
    def describe(self) -> Any:
        ...
    


